### ISSUE TITLE
JSON Download only the choosen status

### ISSUE THREAD

**Issue by scheidelerl** [saw-leipzig/basic.app#12]
Steps to Reproduce: 
1. Open a database with included data
2. Click the JSON - Download Button

It should be possible to consider the status during the download, for example, only load the data with the status unchecked. With a modal will show the choices when clicking the button.

**Comment by ukretschmer** [comment]
Maybe this could be combined with other filters and we should implement a choice between downloading: 

1. all data or
2. data currently displayed

This enables download, e.g. all persons with status `unchecked` or `unsafe` and names starting with 'a'.
